//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdfGenerator.Models.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_mr_IN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_mr_IN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PdfGenerator.Models.Resx.Resources_mr-IN", typeof(Resources_mr_IN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रवेश तारीख.
        /// </summary>
        public static string AdmissionDate {
            get {
                return ResourceManager.GetString("AdmissionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रवेश क्रमांक.
        /// </summary>
        public static string AdmissionNumber {
            get {
                return ResourceManager.GetString("AdmissionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कोणत्या वर्गात प्रवेश घेतला.
        /// </summary>
        public static string AdmittedInClass {
            get {
                return ResourceManager.GetString("AdmittedInClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जन्म स्थान.
        /// </summary>
        public static string BirthPlace {
            get {
                return ResourceManager.GetString("BirthPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जाती.
        /// </summary>
        public static string Caste {
            get {
                return ResourceManager.GetString("Caste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रमाणपत्र प्राप्त तारीख.
        /// </summary>
        public static string CertificateRcvdDate {
            get {
                return ResourceManager.GetString("CertificateRcvdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ज्या वर्गातून सोडले.
        /// </summary>
        public static string ClassFromLeft {
            get {
                return ResourceManager.GetString("ClassFromLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to वर्तणूक / वर्तन.
        /// </summary>
        public static string ConductBehaviour {
            get {
                return ResourceManager.GetString("ConductBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to शाळा सुटण्याची तारीख.
        /// </summary>
        public static string DateOfSchlLeaving {
            get {
                return ResourceManager.GetString("DateOfSchlLeaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जन्म तारीख अंकांमध्ये.
        /// </summary>
        public static string DOBInDigits {
            get {
                return ResourceManager.GetString("DOBInDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जन्म तारीख शब्दात.
        /// </summary>
        public static string DOBInWords {
            get {
                return ResourceManager.GetString("DOBInWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पूर्ण नाव.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मातृभाषा.
        /// </summary>
        public static string MotherTongue {
            get {
                return ResourceManager.GetString("MotherTongue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to राष्ट्रीयत्व.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मागील शाळेचे नाव.
        /// </summary>
        public static string PrevSchlName {
            get {
                return ResourceManager.GetString("PrevSchlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रगती.
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सोडण्याचं कारण.
        /// </summary>
        public static string ReasonForLeaving {
            get {
                return ResourceManager.GetString("ReasonForLeaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कोणास मिळाला.
        /// </summary>
        public static string ReceivedByName {
            get {
                return ResourceManager.GetString("ReceivedByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to धर्म.
        /// </summary>
        public static string Religion {
            get {
                return ResourceManager.GetString("Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पोटजाती.
        /// </summary>
        public static string SubCaste {
            get {
                return ResourceManager.GetString("SubCaste", resourceCulture);
            }
        }
    }
}
