//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdfGenerator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentLCData
    {
        public int Id { get; set; }
        public Nullable<int> AdmissionNo { get; set; }
        public string FullName { get; set; }
        public string Nationality { get; set; }
        public string MotherTongue { get; set; }
        public string Religion { get; set; }
        public string Caste { get; set; }
        public string SubCaste { get; set; }
        public string BirthPlace { get; set; }
        public string DOBInDigits { get; set; }
        public string DOBInWords { get; set; }
        public string PrevSchlName { get; set; }
        public string AdmittedInClass { get; set; }
        public string AdmissionDate { get; set; }
        public string Progress { get; set; }
        public string ConductBehaviour { get; set; }
        public string DateOfSchlLeaving { get; set; }
        public string ClassFromLeft { get; set; }
        public string ReasonForLeaving { get; set; }
        public string CertificateRcvdDate { get; set; }
        public string ReceivedByName { get; set; }
    }
}
